# Generated by Django 3.2.6 on 2021-08-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_remove_destination_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('offers', models.BooleanField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potato.destination')),
            ],
        ),
    ]
