# Generated by Django 3.2.6 on 2021-08-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
