# Generated by Django 3.2.6 on 2021-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0004_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='hotel',
            field=models.ManyToManyField(to='potato.Hotels'),
        ),
    ]
