# Generated by Django 3.2.6 on 2021-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0005_dishes_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
